-- phpMyAdmin SQL Dump
-- version 3.5.7
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Nov 27, 2013 at 11:44 PM
-- Server version: 5.5.29
-- PHP Version: 5.4.10

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `test`
--

-- --------------------------------------------------------

--
-- Table structure for table `christmas_quiz`
--

CREATE TABLE `christmas_quiz` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `Question` varchar(255) NOT NULL,
  `Options` varchar(255) DEFAULT NULL,
  `Answer` varchar(255) DEFAULT NULL,
  `Answer Details` longtext,
  `Source` varchar(255) DEFAULT NULL,
  `Created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Modified` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=92 ;

--
-- Dumping data for table `christmas_quiz`
--

INSERT INTO `christmas_quiz` (`ID`, `Question`, `Options`, `Answer`, `Answer Details`, `Source`, `Created`, `Modified`) VALUES
(1, 'Which Gospel(s) speak of the events surrounding Christ''s birth?', 'Luke | Matthew and Luke | Mark and John | Matthew, Mark, Luke, and John', 'Matthew and Luke', 'Matthew alone includes the story of the magi, as told in chapter two of his Gospel. Luke alone includes the details of the birth of Christ''s cousin, John the Baptist, and of Mary''s visit to her cousin Elizabeth during her own pregnancy. Mark begins in medias res, with Christ''s ministry, and John does too, after first describing Christ as being with God in the beginning.', 'http://www.funtrivia.com/playquiz/quiz148803110ac70.html', '2010-11-30 03:37:28', NULL),
(2, 'How many magi visit Christ after his birth, according to the Bible?', 'None | One | Three | Undisclosed Number', 'Undisclosed Number', 'Christian tradition has numbered the magi at three, probably because three gifts were given (gold, frankincense, and myrrh.) Tradition has even given names to the wise men-- Melchior, Kaspar, and Baltazar. However, the Bible itself does not disclose the number of magi who visited Christ. ', 'http://www.funtrivia.com/playquiz/quiz148803110ac70.html', '2010-11-30 03:37:28', NULL),
(3, 'Where is Christ when the magi come to visit Him?', 'In a house | In the temple | In the manger | In the womb', 'In a house', 'Though our traditional manger scenes usually place the magi at the manger, they did not, in fact, visit Christ until he was a "young child" and came to him in a house. (See Matthew 2:11)', 'http://www.funtrivia.com/playquiz/quiz148803110ac70.html', '2010-11-30 03:38:31', NULL),
(4, 'The magi ask Herod where Christ is to be born. Herod summons his priests and scribes, who know the location of the birth because of the prophecy of this man.', 'Jonah | Joel | Amos | Micah', 'Micah', 'See Micha 5:2 and Matthew 2:6', 'http://www.funtrivia.com/playquiz/quiz148803110ac70.html', '2010-11-30 03:38:31', NULL),
(5, 'In a dream, an angel tells Joseph to name his child Jesus, for it was prophesied that a virgin would give birth and call her son Immanuel. What does Immanuel mean?', 'God with us | God in flesh | Jesus saves | God is born', 'God with us', 'See Matthew 1:23', 'http://www.funtrivia.com/playquiz/quiz148803110ac70.html', '2010-11-30 03:39:27', NULL),
(6, 'Herod''s slaughter of the children two and under, according to Matthew, fulfills a prophecy uttered by what man?', 'Micah | Jeremiah | Jonah | Joel', 'Jeremiah', 'See Jeremiah 31:15', 'http://www.funtrivia.com/playquiz/quiz148803110ac70.html', '2010-11-30 03:39:27', NULL),
(7, 'How much younger was Jesus than his cousin John the Baptist?', 'One year | Twelve days | Six months | Two years', 'Six months', 'See Luke 1:36. John''s mother was Elizabeth, whom Mary visited while she was pregnant with Christ', 'http://www.funtrivia.com/playquiz/quiz148803110ac70.html', '2010-11-30 03:40:22', NULL),
(8, 'Who speaks words to the pregnant Mary that have become a part of the Catholic Church''s "Hail Mary"?', 'Elizabeth | Simeon | Anna | Zechariah', 'Elizabeth', 'When Elizabeth sees Mary, she says, "Blessed art thou among women, and blessed is the fruit of thy womb!" (Luke 1:42). Part of the Hail Mary also comes from Gabriel''s greeting to Mary: "Hail, thou that art highly favored; the Lord is with thee" (Luke 1:28). ', 'http://www.funtrivia.com/playquiz/quiz148803110ac70.html', '2010-11-30 03:40:22', NULL),
(9, 'Where do we find "the magnificat"? ', 'Luke | Mark | Matthew | John', 'Luke', 'This is the name given to Mary''s spontaneous praise, which begins, "My soul magnifies the Lord, And my spirit has rejoiced in God my Savior." (See Luke 1:46-55). ', 'http://www.funtrivia.com/playquiz/quiz148803110ac70.html', '2010-11-30 03:41:08', NULL),
(10, 'Why was Jesus born in Bethlehem, according to the Gospel of Luke?', 'His father went to Bethlehem for a census | That''s where both his parents lived | His mother went to visit Elizabeth | He wasn''t; he was born in Nazareth', 'His father went to Bethlehem for a census', 'See Luke 2:1-6', 'http://www.funtrivia.com/playquiz/quiz148803110ac70.html', '2010-11-30 03:41:08', NULL),
(11, 'Christ was laid in a manger. What is a manger?', 'A barn | A feeding trough | A type of inn | A cave', 'A feeding trough', 'Many non-biblical traditions have Christ being born in a cave, perhaps because animals may have been kept safe in a covering hewn out from rock. Animals may also have, in many cases, been kept on the first floor of a house. A manger is a feeding trough for animals, which Mary used as a cradle.', 'http://www.funtrivia.com/playquiz/quiz148803110ac70.html', '2010-11-30 03:41:39', NULL),
(12, 'The Bible tells us Christ was born in December.', 'True | False', 'False', 'The December 25th nativity date was set for the holiday in the 4th century by the Catholic Church. Some argue that it is an unlikely date because the shepherds were, according to Luke 2:8-9, feeding their flocks in the open fields by night, something unlikely to occur in winter. The Christmas celebration was probably intended to displace the more raunchy rituals of the pagan winter festivals and worship of the sun. ', 'http://www.funtrivia.com/playquiz/quiz148803110ac70.html', '2010-11-30 03:41:39', NULL),
(13, 'How do the shepherds learn of Christ''s birth?', 'They see a new star in the sky | There are no shepherds in the Biblical account | The magi tell them | An angel appears to them', 'An angel appears to them', 'See Luke 2:8-9', 'http://www.funtrivia.com/playquiz/quiz148803110ac70.html', '2010-11-30 03:42:48', NULL),
(14, 'When was Christ circumcised?', 'At birth | At eight days old | At 13 years old | He wasn''t', 'At eight days old', 'Isaac was the first to be circumcised at eight days old, which became the customary time for the circumcision. The "Feast of the Circumcision" falls on January 1st (eight days after the traditional nativity date).', 'http://www.funtrivia.com/playquiz/quiz148803110ac70.html', '2010-11-30 03:42:48', NULL),
(15, 'Who prophesied to Mary that Christ was "destined for the fall and rising of many" and that "a sword" would "pierce" her "own soul also"?', 'Anna | Simeon | Elizabeth | Gabriel', 'Simeon', 'See Luke 2:25-35', 'http://www.funtrivia.com/playquiz/quiz148803110ac70.html', '2010-11-30 03:43:04', NULL),
(16, 'What Christmas plant is "Viscum" used to label?', 'Mistletoe | Holly | Ivy | Sage', 'Mistletoe', NULL, 'http://www.christmastrivia.net/printable-general-trivia', '2010-11-30 03:50:06', '2010-11-30 03:50:06'),
(17, 'The name of Scrooge''s dead business partner?', 'James Willcot | John Mantis | Jacob Marely | Jimmy Booth', 'Jacob Marely', NULL, 'http://www.christmastrivia.net/printable-general-trivia', '2010-11-30 03:50:06', '2010-11-30 03:50:06'),
(18, 'Who tried to steal Christmas from the "Whos of Whoville" in the 1966 cartoon based on the Dr. Seuss Story?', 'The Grinch | The Snowman | Hattie Jacques | Ian Holm', 'The Grinch', NULL, 'http://www.christmastrivia.net/printable-general-trivia', '2010-11-30 03:51:32', '2010-11-30 06:18:17'),
(19, 'Which ocean is Christmas Island in?', 'Pacific Ocean | Atlantic Ocean | Indian Ocean | Arctic Ocean', 'Indian Ocean', NULL, 'http://www.christmastrivia.net/printable-general-trivia', '2010-11-30 03:51:32', '2010-11-30 03:51:32'),
(20, 'Which continent is the turkey from?', 'South America | North America | Europe | Australia', 'North America', NULL, 'http://www.christmastrivia.net/printable-general-trivia', '2010-11-30 03:52:32', '2010-11-30 03:52:32'),
(21, ' In which author''s novel is it "always winter but never Christmas"?', 'C S Lewis | John Masefield | Jacob Marley | Sherlock Homes', 'C S Lewis', NULL, 'http://www.christmastrivia.net/printable-general-trivia', '2010-11-30 03:52:32', '2010-11-30 03:52:32'),
(22, 'Which department store created "Rudolph the Red-Nosed Reindeer"?', 'Dillards | Montgomery-Ward | Macy''s | JC Penny''s', 'Montgomery-Ward', NULL, 'http://www.christmastrivia.net/printable-general-trivia', '2010-11-30 03:53:21', '2010-11-30 03:53:21'),
(23, 'What is the capital of Christmas Island?', 'Jackson | St. John | The Settlement | Boothville', 'The Settlement', NULL, 'http://www.christmastrivia.net/printable-general-trivia', '2010-11-30 03:53:21', '2010-11-30 03:53:21'),
(24, 'What year was the first commercial Christmas card made in?', '1764 | 1843 | 1856 | 1902', '1843', NULL, 'http://www.christmastrivia.net/printable-general-trivia', '2010-11-30 03:54:22', '2010-11-30 03:54:22'),
(25, 'What is the best selling Christmas song ever?', 'Here Comes Santa Claus | Jingle Bells | White Christmas | Silent Night', 'White Christmas', NULL, 'http://www.christmastrivia.net/printable-general-trivia', '2010-11-30 03:54:22', '2010-11-30 03:54:22'),
(26, 'What do traditional Ukrainians put on their Christmas tree for good luck?', 'Candles | A Bird''s Nest | A Spider''s Web | Goose Feathers', 'A Spider''s Web', NULL, 'http://www.christmastrivia.net/printable-general-trivia', '2010-11-30 03:56:07', '2010-11-30 03:56:07'),
(27, 'Which Christmas cartoon was based on a New York Sun editorial?', 'Yes, Virginia There is a Santa Claus | Frosty the Snowman | White Christmas | The Grinch', 'Yes, Virginia There is a Santa Claus', NULL, 'http://www.christmastrivia.net/printable-general-trivia', '2010-11-30 03:56:07', '2010-11-30 03:56:07'),
(28, ' Which of these companies was the first to use Santa Clause in an advertisement?', 'Pepsi | Coca-Cola | 7-Up | Fanta', 'Coca-Cola', NULL, 'http://www.christmastrivia.net/printable-general-trivia', '2010-11-30 03:57:12', '2010-11-30 03:57:12'),
(29, 'Which US president was the first to decorate the White House Christmas tree?', 'Franklin Pierce | Andrew Johnson | George Washington | Abraham Lincoln', 'Franklin Pierce', NULL, 'http://www.christmastrivia.net/printable-general-trivia', '2010-11-30 03:57:12', '2010-11-30 03:57:12'),
(30, 'Which country did the gingerbread house come from?', 'Austria | Switzerland | Germany | United States', 'Germany', NULL, 'http://www.christmastrivia.net/printable-general-trivia', '2010-11-30 03:58:06', '2010-11-30 03:58:06'),
(31, 'In what year was "A Christmas Carol", by Charles Dickens, published?', '1765 | 1843 | 1860 | 1906', '1843', NULL, 'http://www.christmastrivia.net/printable-general-trivia', '2010-11-30 03:58:06', '2010-11-30 03:58:06'),
(32, 'What is the name of the Grinch''s dog in "How the Grinch Stole Christmas"?', 'Pete | Sam | Ruth | Max', 'Max', NULL, 'http://www.christmastrivia.net/printable-general-trivia', '2010-11-30 03:59:41', '2010-11-30 03:59:41'),
(33, 'Which reindeer is Rudolph''s dad?', 'Dancer | Dixon | Donner | Blitzen', 'Donner', NULL, 'http://www.christmastrivia.net/printable-general-trivia', '2010-11-30 03:59:41', '2010-11-30 03:59:41'),
(34, 'What does Alvin want for Christmas?', 'A Bottle of Rum | An iPod | A Hula Hoop | A New Car', 'A Hula Hoop', NULL, 'http://www.christmastrivia.net/printable-general-trivia', '2010-11-30 04:05:00', '2010-11-30 04:05:00'),
(35, 'In which year was “The Twelve Days of Christmas” first printed?', '1323 | 1564 | 1780 | 1849', '1780', 'The printed game of “The Twelve Days of Christmas” appeared for the first time between 1780 and 1800 in two separate editions. The publication was included in an inexpensive collection of games intended not only for Christmas celebration, but for general children''s entertainment. ', 'http://www.funtrivia.com/playquiz/quiz301330227f578.html', '2010-11-30 04:06:55', '2010-11-30 04:09:16'),
(36, 'What do the five golden rings - in the 12 days of Christmas - represent?', 'The first five books of the New Testament | The first five books of the Old Testament | The Olympics rings | Five gifts from the Holy Spirit, the five sacraments', 'The first five books of the Old Testament', 'The rings represent Pentateuch, providing the history of man''s fall from grace.', 'http://www.funtrivia.com/playquiz/quiz301330227f578.html', '2010-11-30 04:06:55', '2010-11-30 04:09:16'),
(37, 'In the 12 Days of Christmas - how many "Lords a Leaping" are there?', '8 | 4 | 6 | 10', '10', 'The 10 Lords a Leaping represent the ten commandments.', 'http://www.funtrivia.com/playquiz/quiz301330227f578.html', '2010-11-30 04:07:52', '2010-11-30 04:07:52'),
(38, 'Canada, The U.K., and most other Commonwealth countries officially celebrate the day after Christmas as a holiday. What is the holiday called?', 'Britain’s Day | Boxing Day | Bearer’s Day | Beer Day', 'Boxing Day', 'Considered a “working man’s” holiday as it was custom for servants to receive the day after Christmas off to have Christmas with their own families. Oftentimes leftovers from the Christmas dinner would be boxed up and sent along with the servants. ', 'http://www.funtrivia.com/playquiz/quiz2772771fbeaa0.html', '2010-11-30 04:12:12', '2010-11-30 04:17:52'),
(39, 'What Christmas song has the line “I don’t know if there’ll be snow, but have a cup of cheer”?', 'Holly Jolly Christmas | Have Yourself a Merry Little Christmas | Here Comes Santa Claus | Here We Come a Wassailing', 'Holly Jolly Christmas', 'Burl Ives sings "Holly Jolly Christmas" for the special "Rudolph the Red Nosed Reindeer" in 1964. The first chorus is: "Have a holly, jolly Christmas. It''s the best time of the year. I don''t know if there''ll be snow, but have a cup of cheer."', 'http://www.funtrivia.com/playquiz/quiz2772771fbeaa0.html', '2010-11-30 04:12:12', '2010-11-30 04:17:58'),
(40, 'What song does Lucy ask Schroeder to play on his piano in “A Charlie Brown Christmas”?', 'Joy to the World | Jingle Bells | Jolly O’ Saint Nicholas | Jesu', 'Jingle Bells', 'Schroeder attempts to play several complex versions of Jingle Bells for Lucy with her dismissing each one with a “No, no, no.” He plunks out a single key version and she yells "That''s it!"', 'http://www.funtrivia.com/playquiz/quiz2772771fbeaa0.html', '2010-11-30 04:13:48', '2010-11-30 04:17:52'),
(41, 'Under what queen’s reign and influence did the modern day Christmas tree tradition begin?', 'Queen Victoria | Queen Elizabeth II | Queen Elizabeth I | Queen Mary I', 'Queen Victoria', 'While the custom of a Christmas tree began in Germany, it wasn''t until Prince Albert, Queen Victoria''s husband, brought the Christmas tree to England in 1840 that it gained popularity there. Several engravings and illustrations appeared in English papers showing the royal family and their many Christmas trees. Due to the popularity of Queen Victoria, the tradition spread as English citizens followed the Royal example.\r\n\r\nQueen Mary I, or Bloody Mary, and Queen Elizabeth I are too early, 1516-1558, and 1533-1603 respectively. Queen Elizabeth II is the current queen.', 'http://www.funtrivia.com/playquiz/quiz2772771fbeaa0.html', '2010-11-30 04:13:48', '2010-11-30 04:17:52'),
(42, 'According to the popular song, what did a reindeer do to grandma?', 'Ratted out | Ridiculed | Raised her | Ran over', 'Ran over', 'According to the song "Grandma got run over by a reindeer, walking home from our house Christmas Eve. You can say there''s no such thing as Santa, but as for me and Grandpa, we believe."\r\n\r\nThe song was written by Randy Brooks, and was originally performed by the husband and wife duo of Elmo and Patsy Shropshire in 1979. After their divorce, Elmo re-recorded the song solo in 1992.', 'http://www.funtrivia.com/playquiz/quiz2772771fbeaa0.html', '2010-11-30 04:14:53', '2010-11-30 04:17:52'),
(43, 'In the Czech Republic what kind of smelly soup is usually eaten on Christmas Eve?', 'Fish | Gumbo | Chicken | Gazpacho', 'Fish', 'Fish soup, usually made of carp, is eaten on Christmas Eve along with potato salad. Ginger breads and cookies are consumed throughout the holiday and exchanged with friends and neighbors. ', 'http://www.funtrivia.com/playquiz/quiz33165025f79f8.html', '2010-11-30 04:19:58', '2010-11-30 04:22:30'),
(44, 'In Finland, almost every family will have a roast Christmas ham served with which of the following condiments?', 'Mayonnaise | Catsup | Mustard | Soy Sauce', 'Mustard', 'In Finland a Christmas Ham is always served with mustard. Carrot casseroles and rutabaga casseroles are common side dishes for Christmas dinner. Rice pudding and prune pastries are common desserts.', 'http://www.funtrivia.com/playquiz/quiz33165025f79f8.html', '2010-11-30 04:19:58', '2010-11-30 04:22:30'),
(45, 'Mulled wine is a popular holiday drink served warm with spices. ', 'True | False', 'True', 'Mulled wine is usually a red wine, spiced, and then served very warm, often with fruit added. The garnish is often a cinnamon stick. It is a popular holiday drink in many parts of the world.', 'http://www.funtrivia.com/playquiz/quiz33165025f79f8.html', '2010-11-30 04:20:17', '2010-11-30 06:34:48'),
(46, 'A "stollen" is a German variety of which Christmas sweet treat? ', 'Eggnog | Pumpkin pie | Fruit cake | Red velvet cake', 'Fruit cake', 'Stollen is a loaf-shaped, frosted, German version of a fruitcake. Stollen was fist mentioned in 15th century writings but has been being made for much longer than that. The cake itself contains very little sugar; the sweetness of the stollen comes from the candied fruit that is added.', 'http://www.funtrivia.com/playquiz/quiz33165025f79f8.html', '2010-11-30 04:20:42', '2010-11-30 04:22:30'),
(47, 'Celebration of the Christmas holiday is commanded in the Christian New Testament scriptures?', 'True | False', 'False', 'Accounts of Christ''s birth are found in the Gospels of Matthew and Luke, but the celebration of Christmas is not commanded. The New Testament church would have been more likely to celebrate Passover than Christmas. The origin of the celebration of the birth of Christ is somewhat later; the first surviving reference to the Christmas celebration comes in 200 A.D., and the nativity date was not fixed until the 4th century. ', 'http://www.funtrivia.com/playquiz/quiz14782010edfa8.html', '2010-11-30 04:23:37', '2010-11-30 04:29:44'),
(48, 'When does the Armenian Orthodox Church celebrate Christmas?', 'January 6 | January 1 | December 25 | December 24', 'January 6', 'Christmas or "The Feast of Nativity" is celebrated on the 6th by Armenian Orthodox but on the 7th by Ethiopian, Russian, and Ukrainian Orthodox. It is celebrated on the 25th by Catholics and Protestants. ', 'http://www.funtrivia.com/playquiz/quiz14782010edfa8.html', '2010-11-30 04:23:37', '2010-11-30 04:29:44'),
(49, 'Who fixed December 25th as the official nativity date?', 'Jesus Christ | Bishop Liberius | Emperor Constantine | Pope Pius', 'Bishop Liberius', 'The December 25th date was fixed by Bishop Liberius of Rome in 354 A.D. ', 'http://www.funtrivia.com/playquiz/quiz14782010edfa8.html', '2010-11-30 04:24:24', '2010-11-30 04:29:44'),
(50, 'The Christmas date may have been set on December 25th in an effort to supplant the worship of what Roman god?', 'Sol Invictus | Mars | Jupiter | Julius Caesar', 'Sol Invictus', 'Sol Invictus was the "unconquered sun god" and was one of the central gods worshiped by the Romans in the 3rd century. Under the Emperor Aurelian, December 25th began to be celebrated as the birthday of the sun god. Christians may have adopted this date in the 4th century in order to refocus worship from the sun god to the Son of God.', 'http://www.funtrivia.com/playquiz/quiz14782010edfa8.html', '2010-11-30 04:24:24', '2010-11-30 04:29:44'),
(51, 'What plant, now used as a symbol of Christmas, was once associated with the Roman god Saturn and later used in Celtic tradition?', 'Holly | Pine | Mistletoe | Fir', 'Holly', 'In ancient Rome, holly was associated with Saturn, the god of the harvest. In Druidic and other related pagan traditions, holly leaves were deposited around homes in order to shelter fairies against the cold. Early Christians, in what later became Great Britain, probably originally adopted this tradition to avoid persecution. Holly has since been reinterpreted with Christian symbolism, and is used to remind Christians of Christ''s crown of thorns. ', 'http://www.funtrivia.com/playquiz/quiz14782010edfa8.html', '2010-11-30 04:25:18', '2010-11-30 04:29:44'),
(52, 'Which of the following was not at the manger in the Biblical account of Christ''s birth?', 'The magi | Joseph | The shepherds | Mary', 'The magi', 'When the wise men finally complete their journey and offer their gifts to Jesus, he is no longer a baby resting in a manger, but a young child in a house. The account of the wise men is found only in the Gospel of Matthew. The number is not mentioned, though Christian tradition sets it at three, and gives traditional names to the wise men: Melchior, Kaspar, and Baltazar.', 'http://www.funtrivia.com/playquiz/quiz14782010edfa8.html', '2010-11-30 04:25:18', '2010-11-30 04:29:44'),
(53, 'According to modern Christian legend, what does the candy cane represent?', 'A shepherd''s staff | Christ''s purity | Christ''s blood | All of these', 'All of these', 'It may well be a mere "preacher''s story," but legend says that a candy maker invented the candy cane as a witness to Christ. It is shaped to resemble a shepherd''s staff, because Christ is the Good Shepherd. The candy is white to represent the purity of Christ, and the red stripes represent His blood. As Isaiah prophesied, "By his stripes we are healed." The flavor of the cane is peppermint, which is similar to hyssop. Hyssop is in the mint family and was used in the Old Testament for purification and sacrifice. "Purge me with hyssop," writes the Psalmist, "and I will be clean. Wash me, and I will be whiter than snow." ', 'http://www.funtrivia.com/playquiz/quiz14782010edfa8.html', '2010-11-30 04:26:05', '2010-11-30 04:29:44'),
(54, 'In the East, St. Nicholas was the patron saint of?', 'Virgins | Women | Sailors | Toymakers', 'Sailors', 'Traditionally, the feast day of Saint Nicholas was observed on December 6th and gifts were given. German Protestants encouraged people to honor instead the Christ child on December 25th. The Christ Child was also depicted as bringing gifts. The German "Christkindl," or Christ child, became Kris Kringle, a popular nickname for Santa Claus. In the West, St. Nicholas has been regarded as the patron saint of children, among other things. ', 'http://www.funtrivia.com/playquiz/quiz14782010edfa8.html', '2010-11-30 04:26:05', '2010-11-30 06:35:21'),
(55, 'Until the mid-20th century what was used for tinsel on Christmas trees?', 'strips of silver | strips of aluminum | strips of gold | strips of tin', 'strips of silver', 'Real silver was used as tinsel for over 300 years. It was rolled out flat and sliced into thin strips. It was used over and over again and passed down through the generations. It tarnished easily and had to be polished every year by hand. In the 19th century lead was added to help the tinsel hang better, but it was removed in the 20th century because of health concerns.', 'http://www.funtrivia.com/playquiz/quiz3196162497108.html', '2010-11-30 04:39:20', '2010-11-30 04:45:21'),
(56, 'In which country did the tradition of the Christmas tree start?', 'China | Germany | Denmark | Scotland', 'Germany', 'The Christmas tree is a Germanic custom that was brought to Great Britain with the Georgian Kings. It caught on quickly with the aristocracy but not with the peasants who looked at it as a foreign custom. It took over 100 years for the practice to become commonplace in Great Britain and its outlying territories.', 'http://www.funtrivia.com/playquiz/quiz3196162497108.html', '2010-11-30 04:39:20', '2010-11-30 04:45:21'),
(57, 'During the 19th and early 20th centuries, the larger your Christmas tree the more status you had among your peers?', 'True | False', 'True', 'For many years, only the tops were cut off trees and used as Christmas trees. They were usually no more than 2-3 ft. tall and usually stood on a table. During the Victorian era this changed as people became fonder of large floor standing Christmas trees and it became a status symbol to have the largest tree in your neighborhood. ', 'http://www.funtrivia.com/playquiz/quiz3196162497108.html', '2010-11-30 04:39:56', '2010-11-30 04:45:21'),
(58, 'What is the name of the company that made the first artificial Christmas tree?', 'Johnson & Johnson | Levi Strauss | Schelgerhoffen | Addis Brush Company', 'Addis Brush Company', 'Around 1900, the Addis Brush Company started producing the first artificial Christmas tree. It was made from the same material that they used for their toilet brushes. The material was simply dyed green. The over cutting of trees for holiday usage had caused legislation to be passed in some areas banning the cutting of live trees for use as Christmas trees. The artificial tree was a hit!', 'http://www.funtrivia.com/playquiz/quiz3196162497108.html', '2010-11-30 04:39:56', '2010-11-30 04:45:21'),
(59, 'In 16th century Poland it was popular to hang your Christmas tree upside down from the ceiling?', 'True | False', 'True', 'As strange as this might sound, it is true. It was considered a Christmas chandelier. This was done in Poland in the 16th century after it was invaded by the Prussians. It was being done in some regions of Germany as far back as the 12th century.', 'http://www.funtrivia.com/playquiz/quiz3196162497108.html', '2010-11-30 04:40:39', '2010-11-30 04:45:21'),
(60, 'What was used to light up a Christmas tree before the advent of electric Christmas lights?', 'jewels | glitter | gas lights | candles', 'candles', 'Candles were used for hundreds of years. They did have the unfortunate side effect of sometimes catching the tree on fire which usually spread and burnt the home down. ', 'http://www.funtrivia.com/playquiz/quiz3196162497108.html', '2010-11-30 04:40:39', '2010-11-30 04:45:21'),
(61, 'The giant Christmas tree seen at Rockefeller Center every year since 1931 is usually what kind of tree?', 'Norway spruce | Scotch pine | Douglas fir | Balsam fir', 'Norway spruce', 'Every year but 4, it has been a Norway spruce. This type of tree has a wonderful shape even when it gets 90 feet tall. Many other evergreen trees lose their triangular shape when they get this tall. It is not the best choice for a 5 foot tall family tree as it does not hold ornaments well when it is a small size tree. The other three choices are better options for home Christmas trees.', 'http://www.funtrivia.com/playquiz/quiz3196162497108.html', '2010-11-30 04:41:19', '2010-11-30 04:45:21'),
(62, 'The Christmas carol "O Tannenbaum", in English "O Christmas Tree", was written by what German composer?', 'Nicolo Paganini | Wolfgang Mozart | Ernst Anschustz | Frederic Chopin', 'Ernst Anschustz', 'Ernst Anschustz is the only German composer of the 4 choices. Mozart was Austrian, Paganini was Italian and Chopin was Polish. Anschustz passed away in 1861 and was most noted as a teacher. "O Tannenbaum" is by far his most well known work. There are other German songs about Christmas trees but his is the one that was translated into English and has been played for over 100 years every Christmas season.', 'http://www.funtrivia.com/playquiz/quiz3196162497108.html', '2010-11-30 04:41:19', '2010-11-30 04:45:21'),
(63, 'According to an National Public Radio reported study on suicides during the holidays, how does the rate in the United States actually compare to the rest of the year?', 'It is up by 50% | There are fewer | It doubles | No Change', 'There are fewer', 'A surprising 2007 study (a meta-analysis of previously reported results), concluded that the suicide rate drops substantially during the holidays. An NPR''s newscaster speculated that Jimmy Stewart''s suicide in the oft viewed film "It''s a Wonderful Life" may be partly responsible for the development of a holiday suicide myth.', 'http://www.funtrivia.com/playquiz/quiz2789751ff0690.html', '2010-11-30 04:51:26', '2010-11-30 04:53:19'),
(64, 'Part of the Christmas tradition for many people is shortbread. Why is it called "short"?', 'No leavening used, it does not rise (is "short") | It does not contain long gluten strands | It was only meant for children ("short" people) | Because of the proportion of fat to flour, you can make it when you are "short" of flour', 'It does not contain long gluten strands', 'Pastry made with shortening does not develop the long gluten chains that occur in other wheat flour products. "Short" is the term we use for a pastry made with a high proportion of semisolid fat (butter, lard, shortening) to flour.', 'http://www.funtrivia.com/playquiz/quiz2789751ff0690.html', '2010-11-30 04:51:26', '2010-11-30 04:53:19'),
(65, 'There is an ancient belief that at midnight on Christmas Eve all water turns to wine?', 'True | False', 'True', NULL, 'http://www.funtrivia.com/playquiz/quiz22415719aa6a0.html', '2010-11-30 04:54:42', '2010-11-30 05:00:14'),
(66, 'In Poland all animals are believed to have the ability to talk at midnight on Christmas Eve, but only for one hour. Not everyone can hear them. Who can?', 'the bad | the children | the ugly | the good', 'the good', NULL, 'http://www.funtrivia.com/playquiz/quiz22415719aa6a0.html', '2010-11-30 04:54:42', '2010-11-30 06:54:53'),
(67, 'In Sweden, it is considered unlucky to be out and about at midnight on Christmas Eve because of something you might meet. What?', 'Trolls celebrating with dancing and revelry | Santa Claus delivering presents | Teddybears having a picnic | Ghosts of departed Vikings', 'Trolls celebrating with dancing and revelry', NULL, 'http://www.funtrivia.com/playquiz/quiz22415719aa6a0.html', '2010-11-30 04:55:42', '2010-11-30 05:00:14'),
(68, 'If you happen to look in the right direction at midnight on Christmas Eve, the location of buried treasure will be revealed. Where is this belief held?', 'parts of Bulgaria and Spain | parts of Wales and Ireland | parts of France and Russia | parts of Canada and China', 'parts of France and Russia', NULL, 'http://www.funtrivia.com/playquiz/quiz22415719aa6a0.html', '2010-11-30 04:55:42', '2010-11-30 05:00:14'),
(69, 'Another tradition from Poland: on Christmas Eve sheaves or handfuls of harvest grain are placed in the four corners of a room to remind the family that Jesus was born in a stable. Which room?', 'kitchen | living room | dining room | bedroom', 'dining room', NULL, 'http://www.funtrivia.com/playquiz/quiz22415719aa6a0.html', '2010-11-30 04:56:51', '2010-11-30 05:00:14'),
(70, 'What did my true love give to me on Christmas Eve?', 'a partridge in a pear tree | nothing | five gold rings | eleven pipers piping', 'nothing', 'Traditionally, the Twelve Days of Christmas start on December 26th (Boxing Day, St Stephen''s Day) and end on Twelfth Night/Twelfth Day (the evening of January 5th through to the end of January 6th).\r\n\r\nThe celebrations did not start until Boxing Day as Christmas Day was considered a holy day and therefore not for merrymaking, so Boxing Day is actually the first day of Christmas in the song.', 'http://www.funtrivia.com/playquiz/quiz22415719aa6a0.html', '2010-11-30 04:56:51', '2010-11-30 05:00:14'),
(71, 'Can you name the popular Christmas song that was actually written for Thanksgiving?', 'Jingle Bells | It Came Upon a Midnight Clear | I Saw Mommy Kissing Santa Claus | Away in the Manger ', 'Jingle Bells', NULL, 'http://www.squidoo.com/christmastriviaquestionsandanswers', '2010-11-30 05:03:38', '2010-11-30 05:03:38'),
(72, 'Electric Christmas tree lights were first used in what year?', '1865 | 1895 | 1905 | 1932', '1895', NULL, 'http://www.squidoo.com/christmastriviaquestionsandanswers', '2010-11-30 05:03:38', '2010-11-30 06:18:30'),
(73, 'Good King Wenceslas was king of what country?', 'Bohemia | England | Germany | Morocco ', 'Bohemia', NULL, 'http://www.squidoo.com/christmastriviaquestionsandanswers', '2010-11-30 05:07:53', '2010-11-30 05:07:53'),
(74, 'Many people are familiar with the term "The Twelve Days of Christmas," but not everyone knows where it originated. Can you pick out the right explanation?', 'Time for Jospeh and Mary to travel to Bethlehem | Time for the wisemen to travel from the East to Jesus | Number of reindeer pulling the sleigh |  Time to celebrate King Wenceslas'' birthday', 'Time for the wisemen to travel from the East to Jesus', NULL, 'http://www.squidoo.com/christmastriviaquestionsandanswers', '2010-11-30 05:07:53', '2010-11-30 05:07:53'),
(82, 'Where is the United State''s national Christmas Tree located?', 'White House | Kings Canyon National Park | Rockafeller Plaza | Downtown Boston', 'Kings Canyon National Park', NULL, 'http://www.squidoo.com/christmastrivia#module12652997', '2010-11-30 05:28:06', '2010-11-30 05:28:06'),
(76, 'Who started the tradition of sending Christmas Cards?', 'Medieval Europeans | English illustrator John Calcott Horsley | German-American printer Louis Prang | Desmond Hallmark', 'Desmond Hallmark', NULL, 'http://www.squidoo.com/christmastriviaquestionsandanswers', '2010-11-30 05:09:48', '2010-11-30 05:09:48'),
(77, 'Who started the tradition of giving gifts on Christmas?', 'The Wisemen who visited Jesus | Ancient Romans hoping for good fortune in the new year | Mark Antony to please Cleopatra | Ancient Greeks seeking to placate the Gods on Olympus', 'Ancient Romans hoping for good fortune in the new year', NULL, 'http://www.squidoo.com/christmastriviaquestionsandanswers', '2010-11-30 05:11:16', '2010-11-30 05:11:16'),
(78, 'What is the guardian angel’s name in "It''s a Wonderful Life"?', 'William | Thomas | Jerry | Clarence', 'Clarence', 'According a It''s a Wonderful Life, every time a bell rings an angel gets his wings.', 'http://www.triviachamp.com/Christmas-Time-Trivia-Questions.php', '2010-11-30 05:17:32', '2010-11-30 06:36:41'),
(79, 'Who wrote The Nightmare Before Christmas?', 'Shel Silverstein | Tim Burton | Dr Seuss | Roald Dahl', 'Tim Burton', 'Burton also wrote Corpse Bride.', 'http://www.triviachamp.com/Christmas-Time-Trivia-Questions.php', '2010-11-30 05:19:03', '2010-11-30 06:16:37'),
(80, ' In the original Home Alone, Kevin is left at home on Christmas Vacation while his parents end up where?', 'New York | London | Paris | Hawaii ', 'Paris', 'In the second Home Alone, he gets lost in New York.', 'http://www.triviachamp.com/Christmas-Time-Trivia-Questions.php', '2010-11-30 05:18:52', '2010-11-30 06:16:37'),
(81, 'What action movie set around Christmas involves terrorists taking over a skyscraper in LA?', 'Blade Runner | Die Hard | Godzilla: Final Wars | The Day After Tomorrow ', 'Die Hard', 'The chief bad guy is named Hans Gruber.', 'http://www.triviachamp.com/Christmas-Time-Trivia-Questions.php', '2010-11-30 05:18:52', '2010-11-30 06:16:37'),
(83, 'Which state was the first to recognize Christmas as a holiday?', 'Maryland | Virgina | Georgia | Alabama', 'Alabama', NULL, 'http://www.squidoo.com/christmastrivia#module12652997', '2010-11-30 05:28:06', '2010-11-30 05:28:06'),
(84, 'Which state was the last to declare Christmas a national holiday?', 'Oklahoma | California | Alaska | North Dakota', 'Oklahoma', NULL, 'http://www.squidoo.com/christmastrivia#module12652997', '2010-11-30 05:28:55', '2010-11-30 05:43:17'),
(85, 'Who delivers gifts to children in Syria?', 'Reindeers | Bears | Small Camels | Hawks', 'Small Camels', 'In Syria Children actually get their gifts on New Year''s Day. They are brought by the smallest camel that brought the Wise Men to the baby Jesus. It is traditional for children to leave water and hay outside of a camel''s house the night before. In the morning the water and hay is gone, replaced by gifts.', 'http://www.squidoo.com/christmastrivia', '2010-11-30 05:32:36', '2010-11-30 05:43:17'),
(86, 'Where did the kissing under the mistletoe tradition begin?', 'Scandinavia | Southern Spain | Eastern Europe | Arkansaw', 'Scandinavia', 'It is associated with a Scandinavian love goddess. ', 'http://www.squidoo.com/christmastrivia', '2010-11-30 05:32:36', '2010-11-30 05:47:28'),
(87, 'What did Chevy Chase plan to buy with his Christmas bonus in National Lampoon''s "Christmas Vacation"?', 'An RV | A Pool | A Red Convertible | A Christmas tree ', 'A Pool', NULL, 'http://www.quizrocket.com/christmas-quiz', '2010-11-30 05:35:25', '2010-11-30 05:45:28'),
(88, 'Where and when did the custom of having and decorating Christmas trees originate?', 'Bremen, Germany circa 1570 | Riga, Latvia 1510 | Oslo, Norway 1525 | In Rockefeller Plaza ', 'Bremen, Germany circa 1570', NULL, NULL, '2010-11-30 05:35:25', '2010-11-30 05:45:28'),
(89, 'What is in a fruitcake?', 'Fruit, nuts, spices | Dust, old bananas, cake | Apples, plums, celery ', 'Fruit, nuts, spices', NULL, 'http://www.quizrocket.com/christmas-quiz', '2010-11-30 05:37:59', '2010-11-30 05:45:28'),
(90, 'Where did the name Santa Claus originate?', '"Sinterklaas", from the Dutch | "Santa Claws", from the colonial British bedtime story | "Santaclause", from the German | "Siintaklass", which means "Christmas" in Finnish ', '"Sinterklaas", from the Dutch', 'After the Reformation, Nicholas'' cult disappeared in all the Protestant countries of Europe except Holland, where his legend persisted as Sinterklaas (a Dutch variant of the name Saint Nicholas). Dutch colonists took this tradition with them to New Amsterdam (now New York City) in the American colonies in the 17th century. ', 'http://www.celebratelove.com/santa.htm', '2010-11-30 05:37:59', '2010-11-30 06:33:04'),
(91, 'What significance is holly in celebrating Christmas?', 'The pointed leaves represent the Christmas star. | The early church band mistletoe, so holly was substituted. | The red berries signify the Crucifixion. | The red berries are a Christmas color. ', 'The early church band mistletoe, so holly was substituted.', NULL, 'http://wilstar.com/xmas/xmasquiz.htm', '2010-11-30 05:48:56', '2010-11-30 06:55:14');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
